# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProjectVersion <- function() {
    invisible(.Call(`_StockInit_ProjectVersion`))
}

InitDF <- function(path, columns, range) {
    .Call(`_StockInit_InitDF`, path, columns, range)
}

